name: Build All Fonts to DEB Package

on:
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environments
        run: |
          apt-get update && apt-get install -y dpkg-dev
          chmod +x ./build.sh
          
      - name: Run build all fonts
        run: |
           ./build.sh FiraCodeFonts    6.2 "FiraCode Font EN" "firacode-font-en"
           ./build.sh JetBrainsMono  2.304 "JetBrainsMono EN" "jetbrainsmono-en"
           ./build.sh MapleMonoNFCN 7.0b36 "Maple Mono NF CN" "maple-mono-nf-cn"
           ./build.sh LxgwWenKai-CN  1.510 "LxgwWenKai NF CN" "lxgw-wenkai-m-cn"
           ./build.sh Sarasa-Gothic 1.0.28 "Sarasa Gothic CN" "sarasa-gothic-cn"
           ./build.sh WenYuanMaruCN  0.600 "Wen Yuan Maru CN" "wen-yuan-maru-cn"
           ./build.sh WenJin-Mincho  1.000 "WenJin Mincho CN" "wenjin-mincho-cn"
      - name: Publish package to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            lingmo-font-firacode-font-en.deb
            lingmo-font-jetbrainsmono-en.deb
            lingmo-font-maple-mono-nf-cn.deb
            lingmo-font-lxgw-wenkai-m-cn.deb
            lingmo-font-sarasa-gothic-cn.deb
            lingmo-font-wen-yuan-maru-cn.deb
            lingmo-font-wenjin-mincho-cn.deb
            
