name: Build All Fonts to DEB Package

on:
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environments
        run: |
          apt-get update && apt-get install -y dpkg-dev
          chmod +x ./build.sh
          
      - name: Run build all fonts
        run: |
           ./build.sh FiraCodeFonts    6.2 "Fira Code Fonts"  "fira-code"
           ./build.sh JetBrainsMono  2.304 "JetBrains Mono"   "jetbrains-mono"
           ./build.sh MapleMonoNFCN 7.0b36 "Maple Mono NF CN" "maple-mono-nf-cn"
           ./build.sh LxgwWenKai-CN  1.510 "Lxgw WenKai"      "lxgw-wen-kai"
           ./build.sh Sarasa-Gothic 1.0.28 "Sarasa Gothic CN" "sarasa-gothic-cn"
      - name: Publish package to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            lingmo-font-fira-code.deb
            lingmo-font-jetbrains-mono.deb
            lingmo-font-maple-mono-nf-cn.deb
            lingmo-font-lxgw-wen-kai.deb
            lingmo-font-sarasa-gothic-cn.deb
            
