name: Build All Fonts to DEB Package

on:
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environments
        run: |
          apt-get update && apt-get install -y dpkg-dev
          chmod +x ./build.sh
          
      - name: Run build all fonts
        run: |
           ./build.sh FiraCodeFonts 6.2 "Fira Code Fonts" "fira-code"
      - name: Publish package to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/*
